### ISSUE TITLE
Where is main.py

### ISSUE THREAD

**Issue by Clebmb** [TheonlyIcebear/SepticX#1]
Is this left out on purpose? Could I get a copy?

**Comment by yattout4** [comment]
nigga

**Comment by yattout4** [comment]
hello discord

**Comment by yattout4** [comment]
icebear is gay

**Comment by yattout4** [comment]
he like penis

**Comment by TheonlyIcebear** [comment]
`compiler.py` is for compiling and the server folder is for the replit, please watch the tutorial. The compiler is not meant for replit nor can it be used it in replit. You need a windows or linux machine to use the program
