### ISSUE TITLE
Discord Link Not Working. The Api Key?

### ISSUE THREAD

**Issue by The-Fate1** [TheonlyIcebear/SepticX#2]
Hey, the discord link is not working so how can I get the key to run the program. And what is the point of the key if the software is free to use anyway.

**Comment by TheonlyIcebear** [comment]
the link is discord.gg/septic

**Comment by The-Fate1** [comment]
![image](https://github.com/TheonlyIcebear/SepticX/assets/88179142/aa0ae20f-0bb0-4c85-9a88-c9e2f61e25db)
Bruhh not like I haven't tried that a billion times

**Comment by TheonlyIcebear** [comment]
I think u might be banned or something
![image](https://github.com/TheonlyIcebear/SepticX/assets/78031685/bddbb9c2-10fb-40e9-ad55-0e0b3bdf6b9b)
I just unbanned everyone try to rejoin

**Comment by The-Fate1** [comment]
Oh thanks. Sorry the issue was on my end. It got fixed when I logged out and login my account.

**Comment by efenatuyo** [comment]
> Oh thanks. Sorry the issue was on my end. It got fixed when I logged out and login my account.

I don't know why yet but sometimes discord decides to temporarly invalidate every invite on your ip
